In [131]:
from numpy import exp, array, random, dot
import copy

class NeuralNetwork():
    def __init__(self):
        # Seed the random number generator, so it generates the same numbers
        # every time the program runs.
        random.seed(1)

        # We model a single neuron, with 3 input connections and 1 output connection.
        # We assign random weights to a 3 x 1 matrix, with values in the range -1 to 1
        # and mean 0.
        self.synaptic_weights = 2 * random.random((3, 1)) - 1

    # The Sigmoid function, which describes an S shaped curve.
    # We pass the weighted sum of the inputs through this function to
    # normalise them between 0 and 1.
    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.
    # It is used on the output of sigmoid.. which is between 0 and 1
    # if x is near 1: means more confidence...near 0 more confidence
    # If it is near 0.5 --> derivative is large and near 0.25
    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    
    # The neural network thinks.
    def think(self, inputs):
        # Pass inputs through our neural network (our single neuron).
        return self.__sigmoid(dot(inputs, self.synaptic_weights))

    # We train the neural network through a process of trial and error.
    # Adjusting the synaptic weights each time.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in xrange(number_of_training_iterations):
            # Pass the training set through our neural network (a single neuron).
            output = self.think(training_set_inputs)

            # Calculate the error (The difference between the desired output
            # and the predicted output).
            error = training_set_outputs - output

            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
            # This means less confident weights are adjusted more.
            # This means inputs, which are zero, do not cause changes to the weights.
            adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))
            
            weight_before_adj = copy.deepcopy(self.synaptic_weights)    
            # Adjust the weights.
            self.synaptic_weights += adjustment
            
            
            print "Iteration",iteration
            print      "Inputs\n",training_set_inputs
            print     "Weights befupd\n", weight_before_adj 
            print "Dot Product before output sig\n",dot(training_set_inputs, weight_before_adj)
            print      " Output\n",output
            print      "Error\n",error
            print      "Sigmoid Derivative\n",self.__sigmoid_derivative(output)
            print "Error Sigmoid Product\n", error * self.__sigmoid_derivative(output)
            print      "Adjustments\n",adjustment
            print       "Weight afterupd\n", self.synaptic_weights
            


In [132]:
#Intialise a single neuron neural network.
neural_network = NeuralNetwork()

In [133]:
print "Random starting synaptic weights: "
print neural_network.synaptic_weights

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [134]:
# The training set. We have 4 examples, each consisting of 3 input values
    # and 1 output value.
training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
print training_set_inputs.T
print training_set_inputs
training_set_outputs = array([[0, 1, 1, 0]]).T

[[0 1 1 0]
 [0 1 0 1]
 [1 1 1 1]]
[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]


In [135]:
# Train the neural network using a training set.
# Do it 10,000 times and make small adjustments each time.
neural_network.train(training_set_inputs, training_set_outputs, 1000)

Iteration 0
Inputs
[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
Weights befupd
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Dot Product before output sig
[[-0.99977125]
 [-0.72507825]
 [-1.16572724]
 [-0.55912226]]
 Output
[[ 0.2689864 ]
 [ 0.3262757 ]
 [ 0.23762817]
 [ 0.36375058]]
Error
[[-0.2689864 ]
 [ 0.6737243 ]
 [ 0.76237183]
 [-0.36375058]]
Sigmoid Derivative
[[ 0.19663272]
 [ 0.21981987]
 [ 0.18116102]
 [ 0.23143609]]
Error Sigmoid Product
[[-0.05289153]
 [ 0.14809799]
 [ 0.13811206]
 [-0.08418501]]
Adjustments
[[ 0.28621005]
 [ 0.06391297]
 [ 0.14913351]]
Weight afterupd
[[ 0.12025406]
 [ 0.50456196]
 [-0.85063774]]
Iteration 1
Inputs
[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
Weights befupd
[[ 0.12025406]
 [ 0.50456196]
 [-0.85063774]]
Dot Product before output sig
[[-0.85063774]
 [-0.22582172]
 [-0.73038368]
 [-0.34607578]]
 Output
[[ 0.29929909]
 [ 0.44378327]
 [ 0.32511054]
 [ 0.41433436]]
Error
[[-0.29929909]
 [ 0.55621673]
 [ 0.67488946]
 [-0.41433436]]
Sigmoid Derivative
[[ 0.20971

In [85]:
print "New synaptic weights after training: "
print neural_network.synaptic_weights

New synaptic weights after training: 
[[ 7.26283009]
 [-0.21614618]
 [-3.41703015]]


In [76]:
# Test the neural network with a new situation.
print "Considering new situation [1, 0, 0] -> ?: "
print neural_network.think(array([1, 0, 0]))

Considering new situation [1, 0, 0] -> ?: 
[ 0.99929937]


In [77]:
# Test the neural network with a new situation.
print "Considering new situation [0, 1, 1] -> ?: "
print neural_network.think(array([0,1,1]))

Considering new situation [0, 1, 1] -> ?: 
[ 0.02575143]
