In [1]:
!ls

house_data.csv	Housing Prices Tensorflow.ipynb


In [2]:
import pandas as pd
import numpy as np

## Basic Analysis

house_data.csv  Housing Prices Tensorflow.ipynb


## NEURAL network code

In [126]:
# Solving supervised learning problem
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [127]:
import tensorflow as tf

In [128]:
#Step 1: Load Data & remove features we dont care about
df = pd.read_csv('house_data.csv').drop(['index','price','sq_price'], axis=1)
df.describe()

area  bathrooms
count    47.000000  47.000000
mean   2000.680851   3.170213
std     794.702354   0.760982
min     852.000000   1.000000
25%    1432.000000   3.000000
50%    1888.000000   3.000000
75%    2269.000000   4.000000
max    4478.000000   5.000000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 5 columns):
index        47 non-null int64
area         47 non-null float64
bathrooms    47 non-null float64
price        47 non-null float64
sq_price     47 non-null float64
dtypes: float64(4), int64(1)
memory usage: 1.9 KB


In [22]:
df.head()

area  bathrooms
0  2104.0        3.0
1  1600.0        3.0
2  2400.0        3.0
3  1416.0        2.0
4  3000.0        4.0

In [20]:
#First running for 10 rows
dataframe = df.head(10)

In [129]:
# Step 2: Add labels
dataframe['buy'] = [1,1,1,0,0,1,0,1,1,1]

In [130]:
dataframe['notbuy'] = dataframe['buy'] == 0

In [131]:
dataframe.head()

area  bathrooms  buy notbuy
0  2104.0        3.0    1  False
1  1600.0        3.0    1  False
2  2400.0        3.0    1  False
3  1416.0        2.0    0   True
4  3000.0        4.0    0   True

In [27]:
# Turn True False to 1/0
dataframe['notbuy'] = dataframe['notbuy'].astype(int)

In [28]:
dataframe.head()

area  bathrooms  buy  notbuy
0  2104.0        3.0    1       0
1  1600.0        3.0    1       0
2  2400.0        3.0    1       0
3  1416.0        2.0    0       1
4  3000.0        4.0    0       1

In [132]:
# Step3 -- Prepare Data for Tensorflow
# To tensors --> generic version of tensors and matrices
# Vectors is a list of numbers: 1 D tensor
# Matrix is a list of list of numbers: 2 d tensor
inputX = dataframe.loc[:,['area','bathrooms']].as_matrix()
inputX = dataframe[['area','bathrooms']].as_matrix()

In [133]:
inputX

array([[  2.10400000e+03,   3.00000000e+00],
       [  1.60000000e+03,   3.00000000e+00],
       [  2.40000000e+03,   3.00000000e+00],
       [  1.41600000e+03,   2.00000000e+00],
       [  3.00000000e+03,   4.00000000e+00],
       [  1.98500000e+03,   4.00000000e+00],
       [  1.53400000e+03,   3.00000000e+00],
       [  1.42700000e+03,   3.00000000e+00],
       [  1.38000000e+03,   3.00000000e+00],
       [  1.49400000e+03,   3.00000000e+00]])

In [37]:
inputY = dataframe[['buy','notbuy']].as_matrix()

In [134]:
inputY

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0]])

In [148]:
# Step 4 -- Write out hyperparameters
learning_rate = 0.00001
training_epochs = 100000
display_steps = 1000
n_samples = inputY.size

In [137]:
# Step 5 - Create computation graph/neural network
# Placeholder for feature input tensors, 
#none --> any number of examples, 
#2 --> no of features
# Placeholders --> gateways for data in computation graphs
x = tf.placeholder(tf.float32,[None,2])


In [138]:
#Create Weights 
# 2x2 float matrix, which is updated during training
# Variables --> hold and update parameters
W= tf.Variable(tf.zeros([2,2]))
print W

Tensor("Variable_17/read:0", shape=(2, 2), dtype=float32)


In [139]:
# Add biases --> like b in y = mx + b
b = tf.Variable(tf.zeros([2]))

In [140]:
# Multiply our weights by our inputs 
# WX + b = Y
y_values = tf.add(tf.matmul(x,W),b)

In [141]:
# APply Softmax to values
# Softmax is our activation function
# IS a probably functoin
y = tf.nn.softmax(y_values)

# Feed in a matrix of labels
y_ = tf.placeholder(tf.float32, [None,2])



In [142]:
# Step 6: Perform training
# Create cost fun.. mean squared error
# Reduce sum.. sum of elements across dimensions
cost = tf.reduce_sum(tf.pow(y_ - y,2)/(2*n_samples))

# Gradient Descent
optimizer = tf.train.GradientDescentOptimizer(
learning_rate).minimize(cost)

In [143]:
# Initialize variables and session
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [149]:
# Training Loop
for i in range(training_epochs):
    sess.run(optimizer, feed_dict={x:inputX,y_:inputY})
    
    # Write out training logs
    if i% display_steps == 0:
        cc = sess.run(cost, feed_dict={x:inputX,y_:inputY})
        print 'training step: %d'%i, "cost=%f"%cc
        
print "optimization finished"
training_cost = sess.run(cost, feed_dict = {x:inputX,y_:inputY})
print "Training COst", training_cost, "\nW=", sess.run(W), '\nb=', sess.run(b)

training step: 0 cost=0.109269
training step: 1000 cost=0.109267
training step: 2000 cost=0.109266
training step: 3000 cost=0.109265
training step: 4000 cost=0.109263
training step: 5000 cost=0.109262
training step: 6000 cost=0.109261
training step: 7000 cost=0.109259
training step: 8000 cost=0.109258
training step: 9000 cost=0.109257
training step: 10000 cost=0.109255
training step: 11000 cost=0.109254
training step: 12000 cost=0.109253
training step: 13000 cost=0.109251
training step: 14000 cost=0.109250
training step: 15000 cost=0.109249
training step: 16000 cost=0.109247
training step: 17000 cost=0.109246
training step: 18000 cost=0.109245
training step: 19000 cost=0.109243
training step: 20000 cost=0.109242
training step: 21000 cost=0.109241
training step: 22000 cost=0.109239
training step: 23000 cost=0.109238
training step: 24000 cost=0.109237
training step: 25000 cost=0.109235
training step: 26000 cost=0.109234
training step: 27000 cost=0.109232
training step: 28000 cost=0.10923

In [150]:
sess.run(y, feed_dict={x:inputX})

array([[ 0.70811123,  0.29188871],
       [ 0.66500646,  0.3349936 ],
       [ 0.73184586,  0.26815417],
       [ 0.64503986,  0.35496008],
       [ 0.77866679,  0.22133318],
       [ 0.70141441,  0.2985855 ],
       [ 0.65913093,  0.34086907],
       [ 0.64950138,  0.35049865],
       [ 0.6452322 ,  0.35476783],
       [ 0.65554589,  0.34445405]], dtype=float32)

In [151]:
sess.run(tf.nn.softmax([1.,2.,3.,4]))
# How to improve # Add a hidden layer



array([ 0.0320586 ,  0.08714432,  0.23688281,  0.64391422], dtype=float32)